### ISSUE TITLE
if a api function is not decorated by protocol attribute like HttpGet, the exception thrown is not clear in message

### ISSUE THREAD

**Issue by zijianhuang** [zijianhuang/webapiclientgen#124]
···
Status: 500
WARNING: Response body: System.NullReferenceException: Object reference not set to an instance of an object.
   at Fonlow.CodeDom.Web.Ts.ClientApiTsFunctionGenAbstract.CreateApiFunction(WebApiDescription description, IPoco2Client poco2TsGen, IDocCommentTranslate poco2CsGen, JSOutput jsOutput) in C:\VsProjects\OpenSource\webapiclientgen\WebApiClientGenCore.Abstract\ClientApiTsFunctionGenAbstract.cs:line 72
   at Fonlow.CodeDom.Web.Ts.ControllersTsClientApiGenBase.CreateCodeDom(WebApiDescription[] webApiDescriptions) in C:\VsProjects\OpenSource\webapiclientgen\WebApiClientGenCore.Abstract\ControllersTsClientApiGenBase.cs:line 182
   at Fonlow.CodeDom.Web.CodeGen.GenerateClientAPIs(String webRootPath, CodeGenSettings settings, WebApiDescription[] webApiDescriptions) in C:\VsProjects\OpenSource\webapiclientgen\WebApiClientGenCore\CodeGen.cs:line 73
   at Fonlow.WebApiClientGen.CodeGenController.TriggerCodeGen(CodeGenSettings settings) in C:\VsProjects\OpenSource\webapiclientgen\DemoCoreWebControllers\Controllers\CodeGenController.cs:line 66
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Host: localhost:5000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.26200; en-AU) PowerShell/7.5.4
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 3025
···

**Comment by zijianhuang** [comment]
now error message:
```
Status: 400
WARNING: Response body: API function DemoWebApi.Controllers.HeroesController.DemoError has no HttpMethod declared when generating C# client code.
```
or TypeScript client code.
